code --install-extension AffenWiesel.matlab-formatter
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension Gimly81.matlab
code --install-extension Gruntfuggly.todo-tree
code --install-extension JaehyunShim.vscode-ros2
code --install-extension James-Yu.latex-workshop
code --install-extension Slaier.matlab-complete
code --install-extension apommel.matlab-interactive-terminal
code --install-extension austin.code-gnu-global
code --install-extension bat67.matlab-extension-pack
code --install-extension bierner.markdown-mermaid
code --install-extension bramvanbilsen.matlab-code-run
code --install-extension cschlosser.doxdocgen
code --install-extension dionmunk.vscode-notes
code --install-extension eamodio.gitlens
code --install-extension formulahendry.code-runner
code --install-extension go2sh.cmake-integration-vscode
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension johnstoncode.svn-scm
code --install-extension lextudio.restructuredtext
code --install-extension marus25.cortex-debug
code --install-extension mcu-debug.debug-tracker-vscode
code --install-extension mcu-debug.memory-view
code --install-extension mcu-debug.rtos-views
code --install-extension mhutchie.git-graph
code --install-extension moshfeu.compare-folders
code --install-extension ms-iot.vscode-ros
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension platformio.platformio-ide
code --install-extension ryanolsonx.solarized
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension smilerobotics.urdf
code --install-extension tomoki1207.pdf
code --install-extension tomoyukim.vscode-mermaid-editor
code --install-extension trond-snekvik.simple-rst
code --install-extension tushortz.python-extended-snippets
code --install-extension twxs.cmake
code --install-extension xaver.clang-format
code --install-extension yzane.markdown-pdf
code --install-extension zxh404.vscode-proto3